services:
  - type: web
    name: db_service
    runtime: python
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fiszki_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: RESET_CODE
        value: "1111"
      - key: ENVIRONMENT
        value: production

databases:
  - name: fiszki_db
    databaseName: fiszki_prod
    region: frankfurt
    plan: starter
    ipAllowList: []  # только внутренний доступ
