services:
  - type: web
    name: db-service
    runtime: python
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fiszki-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: RESET_CODE
        value: "1111"
      - key: CORS_ORIGINS
        value: "https://fiszki-pycharm-vue.onrender.com,http://localhost:8002"
      - key: ENVIRONMENT
        value: production

databases:
  - name: fiszki-db
    databaseName: fiszki
    region: frankfurt
    plan: free
